server:
  port: 5010
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  # mysql
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWD}

  #JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # hibernate logging
  logging:
    level:
      org.hibernate: info #${log.hibernate.level}

  # SERVER AUTO RELOAD
  devtools:
    livereload.enabled: true
  freemarker:
    cache: false

  # JWT Config
  jwt:
    secret: bXNoLWt5bS1jY2cta2p5LWxqaC1qa2gtcGF0cGF0LWdvb2QtbG9zdGFyay13aGF0aXNnb29kLXNzYWZ5LXNsZWVwLW5ld2plYW5zLWZpZ2h0aW5n
    access:
      expiration: 3600000
      header: Authorization

    refresh:
      expiration: 1209600000
      header: Authorization-refresh
#
